data:extend({
  {
    type = "fluid",
    name = "liquid-tin",
    default_temperature = 232,
    heat_capacity = "1KJ",
    base_color = {r=0, g=0.1, b=0.1},
    flow_color = {r=0.1, g=0.1, b=0.1},
    icon = "__Liquid Plastic__/graphics/liquid-plastic.png",
    order = "a[fluid]-b[liquid-plastic]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
    {
    type = "fluid",
    name = "liquid-zinc",
    default_temperature = 420,
    heat_capacity = "1KJ",
    base_color = {r=0, g=0.1, b=0.1},
    flow_color = {r=0.1, g=0.1, b=0.1},
    icon = "__Liquid Plastic__/graphics/liquid-plastic.png",
    order = "a[fluid]-b[liquid-plastic]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
    {
    type = "fluid",
    name = "liquid-lead",
    default_temperature = 327,
    heat_capacity = "1KJ",
    base_color = {r=0, g=0.1, b=0.1},
    flow_color = {r=0.1, g=0.1, b=0.1},
    icon = "__Liquid Plastic__/graphics/liquid-plastic.png",
    order = "a[fluid]-b[liquid-plastic]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "liquid-aluminium",
    default_temperature = 660,
    heat_capacity = "1KJ",
    base_color = {r=0, g=0.1, b=0.1},
    flow_color = {r=0.1, g=0.1, b=0.1},
    icon = "__Liquid Plastic__/graphics/liquid-plastic.png",
    order = "a[fluid]-b[liquid-plastic]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  }
    
})